services:
  e2e:
    build:
      dockerfile: ./Dockerfile
    volumes:
      - ./specs:/usr/src/app/specs
    depends_on:
      - reservations
      - auth
      - payments
      - notifications
      - mongo
  reservations:
    image: ${AWS_PATH}/reservations
    env_file:
      - ../apps/reservations/.env
    ports:
      - '3000:3000'
  auth:
    image: ${AWS_PATH}/auth
    env_file:
      - ../apps/auth/.env
    ports:
      - '3001:3001'
  payments:
    image: ${AWS_PATH}/payments
    ports:
      - '3003:3003'
    env_file:
      - ../apps/payments/.env
  notifications:
    image: ${AWS_PATH}/notifications
    ports:
      - '3004:3004'
    env_file:
      - ../apps/notifications/.env
  mongo:
    image: mongo